### ISSUE TITLE
Add mTLS support for upload to ClickHouse

### ISSUE THREAD

**Issue by sheyt0** [go-graphite/carbon-clickhouse#121]
Hello!
Is it possible to add support for client TLS certificates and (as result) mTLS authentication for upload to ClickHouse?

**Comment by Civil** [comment]
@msaf1980 that's funny coincidence as we were discussing demand for TLS and mTLS on carbonapi side just recently (as part of https://github.com/go-graphite/carbonapi/pull/742 ).

**Comment by msaf1980** [comment]
> Hello! Is it possible to add support for client TLS certificates and (as result) mTLS authentication for upload to ClickHouse?

Possible in the future. After implement on carbonapi, reuse them in carbon-clickhouse for upload/graphite-clickhouse for read.

**Comment by shejt** [comment]
> 

Nice to hear. I'll wait. Thanks!

**Comment by zostrich** [comment]
Hello!
How soon will TLS support be implemented?

**Comment by msaf1980** [comment]
We planned to add it, may be in two month, if have some free time.

**Comment by zostrich** [comment]
will be great! much needed thing

**Comment by msaf1980** [comment]
Already in master. Can you test from master or will be wait next release ?

**Comment by msaf1980** [comment]
v0.11.7 is released. Reopen the issue if you have are problem with this feature,
