### ISSUE TITLE
Tag values converted since 0.11.3 (space replaced with +)

### ISSUE THREAD

**Issue by Hipska** [go-graphite/carbon-clickhouse#124]
Since 0.11.3 tag values that contain a space are now stored with the space replaced by a `+` sign.

This conflicts when having tag values that also have a `+` sign, and this also breaks existing graphite queries where selecting with space was done.

Spaces are allowed: https://graphite.readthedocs.io/en/latest/tags.html#carbon

**Comment by msaf1980** [comment]
@Hipska  Actual issue or mistake ?

**Comment by Hipska** [comment]
Oh sorry, I'm using the telegraf_http_json receiver.

**Comment by msaf1980** [comment]
Yes, bug is reproduce, i'll fix them.

**Comment by Hipska** [comment]
Hi @msaf1980, yes current master looks okay, no more `+` sign in the tag values..
