### ISSUE TITLE
TLS instead mTLS (validate server certificates only)

### ISSUE THREAD

**Issue by zostrich** [go-graphite/carbon-clickhouse#133]
Hello!
Unfortunately, in our installation, the option with mTLS is not very suitable. :-(
Is it possible to validate server certificates only?

**Comment by Civil** [comment]
I'm not sure if anyone tried that, but based on the code: https://github.com/go-graphite/carbon-clickhouse/blob/66e33f862d2b27dfa5e191b205693727979401bd/helper/config/tls.go#L28-L39

You should be able to achive that by just skipping all the client certification part.

**Comment by zostrich** [comment]
> I'm not sure if anyone tried that, but based on the code:
> 
> https://github.com/go-graphite/carbon-clickhouse/blob/66e33f862d2b27dfa5e191b205693727979401bd/helper/config/tls.go#L28-L39
> 
> You should be able to achive that by just skipping all the client certification part (basically don't fill ClientAuth)

client-auth = "" works!)
