### ISSUE TITLE
Missing tag data with after slash separator

### ISSUE THREAD

**Issue by evdevk** [go-graphite/carbon-clickhouse#135]
Starting from carbon-clickhouse-0.11.2-1 and above (carbon-clickhouse-0.11.1-1 working ok) there was some strange bug with uploading metrics.

If I set tag value as symbol/single_symbol - carbon-clickhouse lose single_symbol. If I set tag value as symbol/multiple_symbols - all ok.

Working ok example (check port_name):
```
metric_name;contur=prod&interval=30s;port_name=0/22 123 1703255195
metric_name;contur=prod&interval=30s;port_name=0/x1 123 1703255195
metric_name;contur=prod&interval=30s;port_name=0/.x 123 1703255195
```
Tag1 result list:
port_name=0/22
port_name=0/x1
port_name=0/.x

Bug example (check port_name):
```
metric_name;contur=prod&interval=30s;port_name=0/1 123 1703255195
metric_name;contur=prod&interval=30s;port_name=0/x 123 1703255195
metric_name;contur=prod&interval=30s;port_name=0/. 123 1703255195
```
Tag1 result list:
port_name=0/
port_name=0/
port_name=0/

**Comment by msaf1980** [comment]
@evdevk Can You test against master ? It's may be #116

**Comment by evdevk** [comment]
Looks like not fixed.

1) I've clone master branch
2) gownload go1.18
3) make (binary have 0.11.7) and replace carbon-clickhouse binary
4) push same 3 metrics from example above and got `port_name=0/`

**Comment by evdevk** [comment]
[Here is the code which produces the described error](https://github.com/go-graphite/carbon-clickhouse/blob/66e33f862d2b27dfa5e191b205693727979401bd/helper/escape/url.go#L185)

If you remove "-1" from line - all ok.
